/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.app.jsonc --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 9e1f38b82ddfcd9e1b577d97099a8e7e)
interface __BaseEnv_CloudflareEnv {
  HYPERDRIVE: Hyperdrive;
  HELLO_QUEUE: Queue;
  IMAGES: ImagesBinding;
  ASSETS: Fetcher;
  QUEUE_LOCAL_PUSH_URL: "";
  LOCAL_DEV_PUSH_ENABLED: string;
  NEXTJS_ENV: string;
  CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE: string;
  WORKER_SELF_REFERENCE: Service<typeof import("./.open-next/worker").default>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./.open-next/worker");
  }
  interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "QUEUE_LOCAL_PUSH_URL"
      | "LOCAL_DEV_PUSH_ENABLED"
      | "NEXTJS_ENV"
      | "CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE"
    >
  > {}
}
