/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.app.jsonc --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: d41577be011c57eb8fbe040420b46564)
interface __BaseEnv_CloudflareEnv {
  HYPERDRIVE: Hyperdrive;
  IMAGES: ImagesBinding;
  ASSETS: Fetcher;
  LOCAL_DEV_PUSH_ENABLED: string;
  NEXTJS_ENV: string;
  CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE: string;
  WORKER_SELF_REFERENCE: Service<typeof import("./.open-next/worker").default>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./.open-next/worker");
  }
  interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "LOCAL_DEV_PUSH_ENABLED"
      | "NEXTJS_ENV"
      | "CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE"
    >
  > {}
}
